[package]
name = "dbl-ll"
version = "0.1.0"
authors = ["Simao Gomes Viana <xdevs23@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
